# Generated by Django 2.2.2 on 2019-06-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('fb_user_id', models.CharField(max_length=50)),
                ('fb_token', models.TextField()),
            ],
        ),
    ]
